# Generated by Django 3.1.4 on 2020-12-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_createlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createlist',
            old_name='bid',
            new_name='price',
        ),
        migrations.AddField(
            model_name='createlist',
            name='datecreation',
            field=models.DateField(auto_now=True),
        ),
    ]
