# Generated by Django 3.1.4 on 2020-12-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201215_2247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateList',
        ),
    ]
