# Generated by Django 3.1.4 on 2020-12-16 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_createlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateList',
        ),
    ]
