# Generated by Django 3.1.4 on 2020-12-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_biditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='biditem',
            name='item',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auctions.createlist'),
            preserve_default=False,
        ),
    ]
