# Generated by Django 3.1.4 on 2020-12-17 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_biditem_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.createlist')),
            ],
        ),
    ]
