# Generated by Django 3.1.4 on 2020-12-17 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_itemactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemactive',
            name='id',
        ),
        migrations.AlterField(
            model_name='itemactive',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auctions.createlist'),
        ),
    ]
