# Generated by Django 3.1.4 on 2020-12-17 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201217_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auctions.user')),
                ('items', models.ManyToManyField(to='auctions.CreateList')),
            ],
        ),
    ]
