# Generated by Django 3.1.4 on 2020-12-18 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20201218_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='item',
        ),
        migrations.AddField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.createlist'),
            preserve_default=False,
        ),
    ]
