# Generated by Django 3.1.4 on 2020-12-18 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20201218_0428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
