# Generated by Django 3.1.4 on 2020-12-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20201218_0455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
